# Generated by Django 5.0.1 on 2024-01-11 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bebes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biberones', models.JSONField(default=list)),
                ('agua', models.JSONField(default=list)),
                ('comida', models.JSONField(default=list)),
                ('merienda', models.JSONField(default=dict)),
                ('cena', models.JSONField(default=list)),
                ('bebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bebes.bebe')),
            ],
        ),
    ]
