# Generated by Django 5.0.1 on 2024-01-10 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bebes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actitud', models.CharField(choices=[('alegre', 'Alegre'), ('participativo', 'Participativo/a'), ('inquieto', 'Inquieto/a'), ('tranquilo', 'Tranquilo/a'), ('irritable', 'Irritable'), ('lloron', 'Lloron/a')], max_length=15)),
                ('actividades', models.JSONField(default=list)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('talla', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bebes.bebe')),
            ],
        ),
    ]
