# Generated by Django 5.0.1 on 2024-01-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desarrollo',
            name='comentarios',
            field=models.TextField(default='sin comentarios'),
            preserve_default=False,
        ),
    ]
