# Generated by Django 5.0.1 on 2024-01-10 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bebes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodos', models.JSONField(default=list)),
                ('total_horas_dia', models.DecimalField(decimal_places=2, max_digits=4)),
                ('bebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bebes.bebe')),
            ],
        ),
    ]
